# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='childinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currentcity', models.CharField(max_length=50)),
                ('aadhar', models.BooleanField(default=False)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('guardian', models.CharField(max_length=50)),
            ],
        ),
    ]
