# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='cci',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
