# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_childinfo_cci'),
    ]

    operations = [
        migrations.CreateModel(
            name='typecci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
