# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_typecci'),
    ]

    operations = [
        migrations.CreateModel(
            name='cci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currentcity', models.CharField(max_length=50)),
                ('no_of_children', models.IntegerField(blank=True, null=True)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_children', to='child.typecci')),
            ],
        ),
    ]
