# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_cci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cci',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_cci', to='child.typecci'),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='cci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_children', to='child.cci'),
        ),
    ]
