# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_auto_20180103_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
