# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='lostchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cityfound', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Detail', models.CharField(max_length=500)),
                ('guardian', models.CharField(max_length=50)),
            ],
        ),
    ]
