# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0007_lostchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostchild',
            name='Detail',
            field=models.CharField(max_length=100000),
        ),
    ]
