# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_auto_20180107_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=None, max_length=10)),
                ('Martialstatus', models.CharField(choices=[('Married', 'MARRIED'), ('unmarried', 'UNMARRIED'), ('divorced', 'DIVORCED')], default='unmarried', max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('Job_description', models.CharField(max_length=5000)),
                ('adoptionreason', models.CharField(max_length=5000)),
                ('aadhar', models.BooleanField(default=False)),
                ('childwanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childwanted', to='child.childinfo')),
            ],
        ),
    ]
