# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0009_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default=None, max_length=10)),
                ('Address', models.CharField(max_length=500)),
                ('Occupation', models.CharField(max_length=50)),
                ('Emailid', models.CharField(max_length=50)),
                ('Bank_account_no', models.CharField(max_length=25)),
                ('IFSC_code', models.CharField(max_length=20)),
                ('Aadharcardno', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='sex',
            new_name='Gender',
        ),
    ]
