# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0012_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='State',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='child.state'),
        ),
    ]
