# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0013_childinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childinfo',
            name='State',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
