# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0014_auto_20180110_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childinfo',
            name='State',
        ),
    ]
