# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0015_remove_childinfo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='childinfo',
            name='State',
            field=models.CharField(choices=[('Delhi', 'DELHI'), ('Mumbai', 'MUMBAI'), ('Jaipur', 'JAIPUR'), ('Kolkata', 'KOLKATA')], default='Not known', max_length=10),
        ),
    ]
