# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0016_childinfo_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=30)),
                ('Address', models.TextField()),
            ],
        ),
    ]
