# Generated by Django 2.2.5 on 2019-10-01 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0017_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cci',
            name='typ',
            field=models.ForeignKey(on_delete=True, related_name='list_of_cci', to='child.typecci'),
        ),
        migrations.AlterField(
            model_name='childinfo',
            name='cci',
            field=models.ForeignKey(on_delete=True, related_name='list_of_children', to='child.cci'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=True, related_name='comments', to='child.Post'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='childwanted',
            field=models.ForeignKey(on_delete=True, related_name='childwanted', to='child.childinfo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
